# Generated by Django 4.2.3 on 2023-08-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodels',
            name='last_pub',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
