# Generated by Django 4.2.3 on 2023-08-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_bookmodels_last_pub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodels',
            old_name='catargory',
            new_name='catagory',
        ),
    ]
